# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
class BankInterest(object):


    def __init__(self, summ, period, perc):
        self.summ = summ
        self.period = period
        self.perc = perc

# Differentiated formula
    def diff_int(self):
        arr = []
        mp_cnt = self.period * 12
        rest = self.summ
        mp_real = self.summ / (self.period * 12.0)
        while mp_cnt != 0:
            mp = mp_real + (rest * self.perc / 1200)
            arr.append(round(mp, 2))
            rest = rest - mp_real
            mp_cnt = mp_cnt - 1
        return arr, round(sum(arr), 2)

# Annuity formula
    def ann_int(self):
        mp_cnt = self.period * 12
        r = self.perc / 1200.0
        ak = (r * (1 + r) ** mp_cnt) / (((1 + r) ** mp_cnt) - 1)
        mp = self.summ * ak
        total = mp * mp_cnt
        return round(mp, 2), round(total, 2)

class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(800, 622)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                font = QtGui.QFont()
                font.setFamily("Niagara Engraved")
                self.centralwidget.setFont(font)
                self.centralwidget.setStyleSheet("background-color: rgb(37, 39, 48);")
                self.centralwidget.setObjectName("centralwidget")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(0, 0, 800, 50))
                self.label.setStyleSheet("\n"
        "color: rgb(255, 255, 255);\n"
        "\n"
        "\n"
        "font: 87 23pt \"Arial Black\";")
                self.label.setAlignment(QtCore.Qt.AlignCenter)
                self.label.setObjectName("label")
                self.vvsum = QtWidgets.QLabel(self.centralwidget)
                self.vvsum.setGeometry(QtCore.QRect(0, 90, 400, 50))
                self.vvsum.setStyleSheet("\n"
        "color: rgb(255, 255, 255);\n"
        "\n"
        "\n"
        "font: 87 20pt \"Arial Black\";")
                self.vvsum.setAlignment(QtCore.Qt.AlignCenter)
                self.vvsum.setObjectName("vvsum")
                self.vvsum_2 = QtWidgets.QLabel(self.centralwidget)
                self.vvsum_2.setGeometry(QtCore.QRect(0, 230, 400, 50))
                self.vvsum_2.setStyleSheet("\n"
        "color: rgb(255, 255, 255);\n"
        "\n"
        "\n"
        "font: 87 20pt \"Arial Black\";")
                self.vvsum_2.setAlignment(QtCore.Qt.AlignCenter)
                self.vvsum_2.setObjectName("vvsum_2")
                self.vvsum_3 = QtWidgets.QLabel(self.centralwidget)
                self.vvsum_3.setGeometry(QtCore.QRect(400, 90, 400, 51))
                self.vvsum_3.setStyleSheet("\n"
        "color: rgb(255, 255, 255);\n"
        "\n"
        "\n"
        "font: 87 20pt \"Arial Black\";")
                self.vvsum_3.setAlignment(QtCore.Qt.AlignCenter)
                self.vvsum_3.setObjectName("vvsum_3")
                self.diff = QtWidgets.QRadioButton(self.centralwidget)
                self.diff.setGeometry(QtCore.QRect(400, 150, 391, 51))
                self.diff.setStyleSheet("background-color: rgb(43, 45, 56);\n"
        "color: rgb(255, 255, 255);\n"
        "\n"
        "\n"
        "font: 87 20pt \"Arial Black\";")
                self.diff.setObjectName("diff")
                self.summ = QtWidgets.QLineEdit(self.centralwidget)
                self.summ.setGeometry(QtCore.QRect(60, 150, 251, 51))
                self.summ.setStyleSheet("\n"
        "border: 2px solid rgb(37, 39, 48); border-radius: 20px;\n"
        "color: #FFF;\n"
        "padding-left: 20px;\n"
        "padding-right: 20px;\n"
        "background-color: rgb(34, 36, 44);\n"
        "\n"
        "border: 2px solid rgb(48, 50, 62);\n"
        "\n"
        "border: 2px solid rgb(85, 170, 255); background-color: rgb(43, 45, 56);\n"
        "color: rgb(255, 255, 255);\n"
        "font: 87 13pt \"Arial Black\";")
                self.summ.setObjectName("summ")
                self.proc = QtWidgets.QLineEdit(self.centralwidget)
                self.proc.setGeometry(QtCore.QRect(60, 290, 251, 51))
                self.proc.setStyleSheet("\n"
        "border: 2px solid rgb(37, 39, 48); border-radius: 20px;\n"
        "color: #FFF;\n"
        "padding-left: 20px;\n"
        "padding-right: 20px;\n"
        "background-color: rgb(34, 36, 44);\n"
        "\n"
        "border: 2px solid rgb(48, 50, 62);\n"
        "\n"
        "border: 2px solid rgb(85, 170, 255); background-color: rgb(43, 45, 56);\n"
        "color: rgb(255, 255, 255);\n"
        "font: 87 13pt \"Arial Black\";")
                self.proc.setObjectName("proc")
                self.annuit = QtWidgets.QRadioButton(self.centralwidget)
                self.annuit.setGeometry(QtCore.QRect(400, 200, 391, 51))
                self.annuit.setStyleSheet("background-color: rgb(43, 45, 56);\n"
        "color: rgb(255, 255, 255);\n"
        "\n"
        "\n"
        "font: 87 20pt \"Arial Black\";")
                self.annuit.setObjectName("annuit")
                self.pushButton = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton.setGeometry(QtCore.QRect(480, 350, 241, 71))
                self.pushButton.setStyleSheet("background-color: rgb(43, 45, 56);\n"
        "color: rgb(255, 255, 255);\n"
        "\n"
        "\n"
        "font: 87 20pt \"Arial Black\";")
                self.pushButton.setObjectName("pushButton")
                self.sinm = QtWidgets.QLabel(self.centralwidget)
                self.sinm.setGeometry(QtCore.QRect(0, 520, 400, 50))
                self.sinm.setStyleSheet("\n"
        "color: rgb(255, 255, 255);\n"
        "\n"
        "\n"
        "font: 87 20pt \"Arial Black\";")
                self.sinm.setAlignment(QtCore.Qt.AlignCenter)
                self.sinm.setObjectName("sinm")
                self.sinmred = QtWidgets.QLabel(self.centralwidget)
                self.sinmred.setGeometry(QtCore.QRect(0, 570, 400, 50))
                self.sinmred.setStyleSheet("background-color: rgb(43, 45, 56);\n"
        "color: rgb(255, 255, 255);\n"
        "\n"
        "\n"
        "font: 87 15pt \"Arial Black\";")
                self.sinmred.setAlignment(QtCore.Qt.AlignCenter)
                self.sinmred.setObjectName("sinmred")
                self.vseg = QtWidgets.QLabel(self.centralwidget)
                self.vseg.setGeometry(QtCore.QRect(400, 520, 400, 50))
                self.vseg.setStyleSheet("\n"
        "color: rgb(255, 255, 255);\n"
        "\n"
        "\n"
        "font: 87 20pt \"Arial Black\";")
                self.vseg.setAlignment(QtCore.Qt.AlignCenter)
                self.vseg.setObjectName("vseg")
                self.vsegred = QtWidgets.QLabel(self.centralwidget)
                self.vsegred.setGeometry(QtCore.QRect(400, 570, 400, 50))
                self.vsegred.setStyleSheet("background-color: rgb(43, 45, 56);\n"
        "color: rgb(255, 255, 255);\n"
        "\n"
        "\n"
        "font: 87 15pt \"Arial Black\";")
                self.vsegred.setAlignment(QtCore.Qt.AlignCenter)
                self.vsegred.setObjectName("vsegred")
                self.vvsum_4 = QtWidgets.QLabel(self.centralwidget)
                self.vvsum_4.setGeometry(QtCore.QRect(10, 370, 400, 50))
                self.vvsum_4.setStyleSheet("\n"
        "color: rgb(255, 255, 255);\n"
        "\n"
        "\n"
        "font: 87 20pt \"Arial Black\";")
                self.vvsum_4.setAlignment(QtCore.Qt.AlignCenter)
                self.vvsum_4.setObjectName("vvsum_4")
                self.srok = QtWidgets.QLineEdit(self.centralwidget)
                self.srok.setGeometry(QtCore.QRect(60, 430, 251, 51))
                self.srok.setStyleSheet("\n"
        "border: 2px solid rgb(37, 39, 48); border-radius: 20px;\n"
        "color: #FFF;\n"
        "padding-left: 20px;\n"
        "padding-right: 20px;\n"
        "background-color: rgb(34, 36, 44);\n"
        "\n"
        "border: 2px solid rgb(48, 50, 62);\n"
        "\n"
        "border: 2px solid rgb(85, 170, 255); background-color: rgb(43, 45, 56);\n"
        "color: rgb(255, 255, 255);\n"
        "font: 87 13pt \"Arial Black\";")
                self.srok.setObjectName("srok")
                MainWindow.setCentralWidget(self.centralwidget)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)
                self.add_functions()
                

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "Кредитный калькулятор"))
                self.label.setText(_translate("MainWindow", "Кредитный калькулятор"))
                self.vvsum.setText(_translate("MainWindow", "Введите сумму"))
                self.vvsum_2.setText(_translate("MainWindow", "Введите процент"))
                self.vvsum_3.setText(_translate("MainWindow", "Выберите тип платежей"))
                self.diff.setText(_translate("MainWindow", "Дифференцированные "))
                self.annuit.setText(_translate("MainWindow", "Аннуитентные"))
                self.pushButton.setText(_translate("MainWindow", "Рассчитать"))
                self.sinm.setText(_translate("MainWindow", "Сумма в месяц"))
                self.sinmred.setText(_translate("MainWindow", "~"))
                self.vseg.setText(_translate("MainWindow", "Сумма с процентами "))
                self.vsegred.setText(_translate("MainWindow", "~"))
                self.vvsum_4.setText(_translate("MainWindow", "Введите срок кредита (г)"))


        def add_functions(self):
                self.pushButton.clicked.connect(self.raschet)
                

        def raschet(self):
                try:
                        cymma =  int(self.summ.text())
                except ValueError:
                        cymma = -1
                        self.sinmred.setText('Ошибкааа')
                        self.vsegred.setText('Ошибкааа')
                
                try:
                        procenty = int(self.proc.text())
                except ValueError:
                        procenty = -1
                        self.sinmred.setText('Ошибкааа')
                        self.vsegred.setText('Ошибкааа')
                try:
                        srok =  int(self.srok.text())
                except ValueError:
                        srok = -1
                        self.sinmred.setText('Ошибкааа')
                        self.vsegred.setText('Ошибкааа')
                
                if not (self.diff.isChecked() or self.annuit.isChecked()):
                        self.sinmred.setText('Пипец')
                        self.vsegred.setText('Пипец')
                if (cymma != -1 and procenty != -1 and srok != -1):
                        a = BankInterest(cymma, srok, procenty)
                        if self.diff.isChecked():
                                arr, total = a.diff_int()
                                self.sinm.setText("Сумма в 1 месяц")
                                self.sinmred.setText(str(arr[0]) + ' р')
                                self.vsegred.setText(str(total) + ' р')

                        if self.annuit.isChecked():
                                mp, total = a.ann_int()
                                self.sinm.setText("Сумма в месяц")
                                self.sinmred.setText(str(mp) + ' р')
                                self.vsegred.setText(str(total) + ' р')





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
